name: CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Azure credentials
        run: echo '${{ secrets.AZURE_CREDENTIALS }}' > azure-credentials.json

      - name: Set up Azure credentials
        run: echo 'export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"' >> $GITHUB_ENV
      
      - name: Set up Azure credentials
        run: echo 'export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"' >> $GITHUB_ENV
      
      - name: Set up Azure credentials
        run: echo 'export ARM_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}"' >> $GITHUB_ENV


      - name: Terraform init
        run: |
          export ARM_SUBSCRIPTION_ID="7667bfd6-4676-4837-8d8c-f6f1bf9bc870"
          export ARM_CLIENT_ID="2fff09bd-b095-47e5-af11-56113f31d7ca"
          export ARM_CLIENT_SECRET="Zb28Q~79PIAVFrKJnIlzn3LVCCeE~T62FyG-3bVe"
          export ARM_TENANT_ID="ba351225-3ca4-45f4-b7cc-ff5556c74a3e"
          terraform init -upgrade

      - name: Terraform validate
        run: |
          terraform validate
              
      - name: Set up Azure credentials
        run: echo '${{ secrets.AZURE_CREDENTIALS }}' > azure-credentials.json
        
      - name: Terraform plan
        run: |
          export ARM_SUBSCRIPTION_ID="7667bfd6-4676-4837-8d8c-f6f1bf9bc870"
          export ARM_CLIENT_ID="2fff09bd-b095-47e5-af11-56113f31d7ca"
          export ARM_CLIENT_SECRET="Zb28Q~79PIAVFrKJnIlzn3LVCCeE~T62FyG-3bVe"
          export ARM_TENANT_ID="ba351225-3ca4-45f4-b7cc-ff5556c74a3e"
          terraform plan
     
      - name: Set up Azure credentials
        run: echo '${{ secrets.AZURE_CREDENTIALS }}' > azure-credentials.json
     
      - name: Terraform apply
        run: |
          export ARM_SUBSCRIPTION_ID="7667bfd6-4676-4837-8d8c-f6f1bf9bc870"
          export ARM_CLIENT_ID="2fff09bd-b095-47e5-af11-56113f31d7ca"
          export ARM_CLIENT_SECRET="Zb28Q~79PIAVFrKJnIlzn3LVCCeE~T62FyG-3bVe"
          export ARM_TENANT_ID="ba351225-3ca4-45f4-b7cc-ff5556c74a3e"
          terraform apply -input=false -auto-approve
          
    permissions:
     contents: 'read'
     id-token: 'write'
